### PR TITLE
a2oj ladder solved 1/1

### PR DESCRIPTION
**Pull request by rahulsherwan366**
Solution Of the problem "https://a2oj.com/p?ID=1"

### CODE REVIEW

**Comment by rohitsherwan366** [comment]
> Solution Of the problem "https://a2oj.com/p?ID=1"
Kindly make comments also. So, that it is easy for anyone to understand.

**Comment by rahulsherwan366** [comment]
> > Solution Of the problem "https://a2oj.com/p?ID=1"
> > Kindly make comments also. So, that it is easy for anyone to understand.

Ok. I will do that.

**Comment by rohitsherwan366** [comment]
what is the status of 1/2.

**Comment by rahulsherwan366** [comment]
> what is the status of 1/2.

It is being solved.

**Pull request merged**
